version: "3"
services:
  client:
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    volumes:
      - "./server:/app"
      - "/app/node_modules"